name: Doxygen

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: sudo apt-get install -y doxygen graphviz

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        touch ${{github.workspace}}/build/doc/html/.nojekyll

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        branch: gh-pages
        folder: ${{github.workspace}}/build/doc/html


